################################
# Variables you need to change #
################################

ingroup: "hetAtr" # the name/code for your ingroup species  
genome: "directory/to/genome.fa"  # the location of the reference genome

####################################
# Variables you may need to change #
####################################

# decide if LD pruning parameters should be configurable ..?
