################################
# Variables you need to change #
################################

spp: "hetAtr" # the name/code for your ingroup species

####################################
# Variables you may need to change #
####################################

# decide if LD pruning parameters should be configurable ..?
